name: grafika_cafe
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  cloud_firestore: ^3.1.12
  cupertino_icons: ^1.0.2
  dropdown_search: ^3.0.1
  firebase: ^9.0.2
  firebase_auth: ^3.3.14
  firebase_storage: ^10.2.12
  flutter:
    sdk: flutter
  get: 4.6.1
  image_picker: ^0.8.5+3
  nb_utils: ^4.4.17

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
